"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { addMinutes, format, startOfDay } from "date-fns";
import { ja } from "date-fns/locale";
import { AlarmClock, BarChart3, CalendarDays, Check, CirclePlus, Gamepad2, Home, ListTodo, Menu, Moon, RefreshCw, Route, Settings, Sparkles, Sunrise, Target } from "lucide-react";
import type { PlanBlock, TaskInput } from "@/lib/domain/types";
import { calculateDisposableTime, calculateWakePlan, createFallbackPlan, getCurrentAndNext, rescheduleAfterDelay } from "@/lib/domain/scheduler";
import { LifeCoachChat } from "@/components/life-coach-chat";

type Tab = "now"|"today"|"add"|"calendar"|"more";
type LocalState = { tasks:TaskInput[]; blocks:PlanBlock[]; game:{active:boolean;startedAt?:string;plannedEnd?:string;sessions:number}; routineDone:string[]; growth:string[] };
type QueuedRequest={url:string;method:"POST"|"PATCH"|"DELETE";body?:unknown};
function queueRequest(request:QueuedRequest){const key="chronopilot-offline-queue";const current=JSON.parse(localStorage.getItem(key)??"[]") as QueuedRequest[];localStorage.setItem(key,JSON.stringify([...current,request]));}
async function sendOrQueue(request:QueuedRequest){if(!navigator.onLine){queueRequest(request);return null}try{const response=await fetch(request.url,{method:request.method,headers:{"content-type":"application/json"},body:request.body===undefined?undefined:JSON.stringify(request.body)});if(!response.ok)throw new Error("sync failed");return response}catch(error){if(error instanceof TypeError){queueRequest(request);return null}throw error}}
const initialTasks:TaskInput[]=[
  {id:"t1",title:"査読コメントを整理する",estimateMinutes:40,priority:4,required:true},
  {id:"t2",title:"回答書を修正する",estimateMinutes:50,priority:4,required:true},
  {id:"t3",title:"設計メモを作成する",estimateMinutes:30,priority:2}
];
function freshState():LocalState { const now=new Date(); const base=startOfDay(now); const fixed:PlanBlock[]=[
  {id:"meal",title:"夕食と休憩",kind:"meal",startsAt:addMinutes(base,19*60).toISOString(),endsAt:addMinutes(base,19*60+45).toISOString(),status:"planned",fixed:true},
  {id:"sleep",title:"就寝",kind:"sleep",startsAt:addMinutes(base,24*60).toISOString(),endsAt:addMinutes(base,31*60).toISOString(),status:"planned",fixed:true}
]; return {tasks:initialTasks,blocks:createFallbackPlan(now,initialTasks,fixed,now),game:{active:false,sessions:0},routineDone:[],growth:["分散システムを30分学ぶ","AIアプリの運用メモを書く"]}; }
const tabItems=[{id:"now" as const,label:"今",icon:Home},{id:"today" as const,label:"今日",icon:ListTodo},{id:"add" as const,label:"追加",icon:CirclePlus},{id:"calendar" as const,label:"カレンダー",icon:CalendarDays},{id:"more" as const,label:"その他",icon:Menu}];

export function Dashboard({demo,email}:{demo:boolean;email:string}) {
  const [tab,setTab]=useState<Tab>("now"); const [now,setNow]=useState<Date|null>(null); const [state,setState]=useState<LocalState>(freshState); const [toast,setToast]=useState("");
  useEffect(()=>{ const flush=async()=>{const key="chronopilot-offline-queue";const queued=JSON.parse(localStorage.getItem(key)??"[]") as QueuedRequest[];const remaining:QueuedRequest[]=[];for(const request of queued){try{await sendOrQueue(request)}catch{remaining.push(request)}}localStorage.setItem(key,JSON.stringify(remaining))};const start=setTimeout(async()=>{setNow(new Date());const saved=localStorage.getItem("chronopilot-state");if(saved)try{setState(JSON.parse(saved) as LocalState)}catch{}if(!demo){void flush();const response=await fetch("/api/tasks");if(response.ok){const rows=await response.json() as Array<{id:string;title:string;estimate_minutes:number;priority:1|2|3|4;due_at?:string;required?:boolean}>;const tasks=rows.map(row=>({id:row.id,title:row.title,estimateMinutes:row.estimate_minutes,priority:row.priority,dueAt:row.due_at,required:row.required}));setState(s=>({...s,tasks,blocks:createFallbackPlan(new Date(),tasks,s.blocks.filter(b=>b.fixed),new Date())}))}}},0); const timer=setInterval(()=>setNow(new Date()),1000);window.addEventListener("online",flush);return()=>{clearTimeout(start);clearInterval(timer);window.removeEventListener("online",flush)}; },[demo]);
  useEffect(()=>{ if(now)localStorage.setItem("chronopilot-state",JSON.stringify(state)); },[state,now]);
  const active=useMemo(()=>now?getCurrentAndNext(state.blocks,now):{current:undefined,next:undefined,remainingMinutes:0},[state.blocks,now]);
  function message(value:string){setToast(value);setTimeout(()=>setToast(""),3000)}
  function completeCurrent(){ if(!active.current)return; const id=active.current.id;setState(s=>({...s,blocks:s.blocks.map(b=>b.id===id?{...b,status:"done"}:b),tasks:s.tasks.filter(t=>t.id!==id)}));if(!demo)void sendOrQueue({url:`/api/tasks/${id}`,method:"PATCH",body:{status:"completed"}}).catch(()=>{});message("完了しました。次の行動へ進みます"); }
  function replan(delay=0){ setState(s=>({...s,blocks:delay&&now?rescheduleAfterDelay(s.blocks,now,delay):createFallbackPlan(new Date(),s.tasks,s.blocks.filter(b=>b.fixed),new Date())}));message(delay?`${delay}分の変更を反映しました。睡眠は維持しています。`:"現在の予定から再計画しました"); }
  return <div className="app-shell">
    <aside className="desktop-side"><div style={{fontWeight:800,fontSize:20,margin:"0 12px 28px"}}>ChronoPilot</div>{tabItems.map(({id,label})=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}<small className="muted" style={{marginTop:"auto",padding:12}}>{demo?"デモモード":email}</small></aside>
    <main className="content">
      {toast&&<div role="status" className="card" style={{position:"fixed",zIndex:30,top:16,left:"50%",transform:"translateX(-50%)",padding:"12px 16px",width:"max-content",maxWidth:"90%"}}>{toast}</div>}
      {tab==="now"&&<NowView now={now} current={active.current} next={active.next} remaining={active.remainingMinutes} state={state} setState={setState} complete={completeCurrent} replan={replan} message={message} demo={demo}/>} 
      {tab==="today"&&<TodayView now={now} state={state}/>} 
      {tab==="add"&&<AddView demo={demo} setState={setState} onDone={()=>{replan();setTab("today")}} message={message}/>} 
      {tab==="calendar"&&<CalendarView blocks={state.blocks} demo={demo}/>}
      {tab==="more"&&<MoreView state={state} setState={setState} message={message} demo={demo}/>} 
    </main>
    <nav className="nav" aria-label="主要ナビゲーション">{tabItems.map(({id,label,icon:Icon})=><button key={id} className={`${tab===id?"active":""} ${id==="add"?"add":""}`} onClick={()=>setTab(id)} aria-label={label}><Icon size={id==="add"?26:21}/>{id!=="add"&&<span>{label}</span>}</button>)}</nav>
  </div>;
}

function NowView({now,current,next,remaining,state,setState,complete,replan,message,demo}:{now:Date|null;current?:PlanBlock;next?:PlanBlock;remaining:number;state:LocalState;setState:React.Dispatch<React.SetStateAction<LocalState>>;complete:()=>void;replan:(n?:number)=>void;message:(v:string)=>void;demo:boolean}){
  const disposable=calculateDisposableTime({remainingMinutes:Math.max(0,24*60-(now?now.getHours()*60+now.getMinutes():0)),sleepMinutes:420,fixedMinutes:90,travelMinutes:30,lifeMinutes:90,requiredTaskMinutes:state.tasks.filter(t=>t.required).reduce((n,t)=>n+t.estimateMinutes,0),growthMinutes:30,bufferMinutes:20,uncertainMinutes:15,desiredGameMinutes:90});
  const shown=current??next; const free=!shown;
  function toggleGame(){ const date=new Date(); if(state.game.active){if(!demo)void sendOrQueue({url:"/api/records",method:"POST",body:{table:"game_sessions",name:"ゲーム",occurredAt:state.game.startedAt,data:{startedAt:state.game.startedAt,endedAt:date.toISOString(),plannedEnd:state.game.plannedEnd}}}).catch(()=>{});setState(s=>({...s,game:{active:false,sessions:s.game.sessions+1}}));message("ゲームを記録しました。楽しめた時間も大切な休息です");replan(0)}else{const mins=disposable.safeGameMinutes;setState(s=>({...s,game:{...s.game,active:true,startedAt:date.toISOString(),plannedEnd:addMinutes(date,mins).toISOString()}}));message(`${mins}分のゲーム時間を開始しました`)} }
  return <><div className="clock" suppressHydrationWarning>{now?format(now,"H:mm"):"--:--"}</div><section className="card hero">
    <div className="eyebrow">{state.game.active?"ゲーム中":free?"今は自由時間です":"今やること"}</div>
    <h1>{state.game.active?"安心してゲームを楽しむ":free?`ゲームを${disposable.safeGameMinutes}分できます`:shown?.title}</h1>
    {shown&&!state.game.active&&<p className="muted">{format(new Date(shown.startsAt),"H:mm")}〜{format(new Date(shown.endsAt),"H:mm")} · {current?`残り${remaining}分`:"次の行動"}</p>}
    {free&&<p className="muted">この時間までなら睡眠と必須予定には影響しません。</p>}
    {state.game.active&&<p className="muted">終了予定 {state.game.plannedEnd?format(new Date(state.game.plannedEnd),"H:mm"):"--:--"}。延長しても責めずに再計画します。</p>}
    {next&&current&&<p>この後：{format(new Date(next.startsAt),"H:mm")}から {next.title}</p>}
    <div className="button-row">{state.game.active?<button className="button" onClick={toggleGame}><Check size={18}/>ゲームを終える</button>:shown?<><button className="button" onClick={complete}><Check size={18}/>できた</button><button className="button secondary" onClick={()=>replan(15)}>15分延期</button></>:<button className="button" onClick={toggleGame}><Gamepad2 size={18}/>ゲームを始める</button>}<button className="button ghost" onClick={()=>replan()}><RefreshCw size={17}/>再計画</button></div>
  </section><LifeCoachChat blocks={state.blocks} tasks={state.tasks} freeMinutes={disposable.freeMinutes}/><div className="section-title"><h2>今日の余白</h2><span className="pill">推定</span></div><div className="metric-grid"><Metric label="総残り" value={minutes(disposable.totalRemainingMinutes)}/><Metric label="必須作業" value={minutes(disposable.requiredMinutes)}/><Metric label="自由時間" value={minutes(disposable.freeMinutes)}/><Metric label="安心ゲーム" value={minutes(disposable.safeGameMinutes)}/></div></>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span className="muted">{label}</span><strong>{value}</strong></div>}
function minutes(value:number){return value>=60?`${Math.floor(value/60)}時間${value%60?`${value%60}分`:""}`:`${value}分`}

function TodayView({now,state}:{now:Date|null;state:LocalState}){ const done=state.blocks.filter(b=>b.status==="done").length; return <><div className="eyebrow">{now?format(now,"M月d日 EEEE",{locale:ja}):"今日"}</div><div className="section-title"><h1 style={{margin:0}}>今日</h1><span className="pill">{state.blocks.length?Math.round(done/state.blocks.length*100):0}% 完了</span></div><div className="card timeline">{state.blocks.map(block=><div className="timeline-item" key={block.id}><small>{format(new Date(block.startsAt),"H:mm")}</small><span className={`timeline-line ${block.status==="active"?"active":""}`}/><div><strong style={{textDecoration:block.status==="done"?"line-through":"none"}}>{block.title}</strong><div className="muted" style={{fontSize:13}}>{kindName(block.kind)} · {minutes(Math.max(0,(new Date(block.endsAt).getTime()-new Date(block.startsAt).getTime())/60000))}</div></div></div>)}</div></> }
function kindName(kind:PlanBlock["kind"]){return ({sleep:"睡眠",routine:"ルーティン",event:"予定",travel:"移動",task:"必須タスク",meal:"食事",break:"休憩",growth:"成長",game:"ゲーム",free:"自由時間"})[kind]}

function AddView({demo,setState,onDone,message}:{demo:boolean;setState:React.Dispatch<React.SetStateAction<LocalState>>;onDone:()=>void;message:(v:string)=>void}){
  const [mode,setMode]=useState<"natural"|"form">("natural"); const [text,setText]=useState("明日14時から大学で田中先生と打ち合わせ\n移動50分\n15分前に着きたい\n資料準備30分"); const [loading,setLoading]=useState(false);
  async function persist(task:TaskInput){if(demo)return task;const body={title:task.title,estimateMinutes:task.estimateMinutes,priority:task.priority,dueAt:""};if(!navigator.onLine){queueRequest({url:"/api/tasks",method:"POST",body});return task}const response=await sendOrQueue({url:"/api/tasks",method:"POST",body});if(!response) return task;const row=await response.json() as {id:string};return {...task,id:row.id}}
  async function addNatural(){setLoading(true);try{let title=text.split("\n")[0]||"新しい予定";let estimate=Number(text.match(/(?:準備|作業)(\d+)分/)?.[1]??30);if(!demo){const res=await fetch("/api/ai/decompose",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text})});if(res.ok){const json=await res.json() as {preparationTasks?:{title:string;estimateMinutes:number}[];event?:{title:string}};title=json.preparationTasks?.[0]?.title??json.event?.title??title;estimate=json.preparationTasks?.[0]?.estimateMinutes??estimate;}}const task=await persist({id:crypto.randomUUID(),title,estimateMinutes:estimate,priority:3,required:true});setState(s=>({...s,tasks:[...s.tasks,task]}));message("予定と準備タスクへ分解しました");onDone();}catch{message("保存できませんでした。通信を確認してください")}finally{setLoading(false)}}
  async function submitForm(form:FormData){try{const task=await persist({id:crypto.randomUUID(),title:String(form.get("title")),estimateMinutes:Number(form.get("minutes")),priority:Number(form.get("priority")) as 1|2|3|4,required:Boolean(form.get("required"))});setState(s=>({...s,tasks:[...s.tasks,task]}));message("タスクを追加しました");onDone()}catch{message("保存できませんでした。通信を確認してください")}}
  return <><div className="eyebrow">Quick capture</div><h1>追加</h1><div className="button-row" style={{marginBottom:16}}><button className={`button ${mode!=="natural"?"secondary":""}`} onClick={()=>setMode("natural")}><Sparkles size={17}/>自然文</button><button className={`button ${mode!=="form"?"secondary":""}`} onClick={()=>setMode("form")}>通常フォーム</button></div><section className="card">{mode==="natural"?<><div className="field"><label htmlFor="natural">予定やタスクをそのまま入力</label><textarea id="natural" value={text} onChange={e=>setText(e.target.value)}/></div><p className="muted" style={{fontSize:13}}>予定・準備・移動・到着余裕へ分解します。AI未設定時は安全な簡易解析を使います。</p><button className="button" disabled={loading||!text.trim()} onClick={addNatural}>{loading?"分解中…":"分解して追加"}</button></>:<form action={submitForm}><div className="field"><label>タイトル</label><input required name="title" maxLength={200}/></div><div className="field"><label>見積もり（分）</label><input required name="minutes" type="number" min="5" max="1440" defaultValue="30"/></div><div className="field"><label>優先度</label><select name="priority" defaultValue="2"><option value="1">低</option><option value="2">通常</option><option value="3">高</option><option value="4">最優先</option></select></div><label><input type="checkbox" name="required"/> 今日の必須タスク</label><div><button className="button" style={{marginTop:18}}>追加する</button></div></form>}</section></>;
}

type GoogleEvent={id:string;title:string;starts_at:string;ends_at:string;location?:string;external_calendar_id:string;status?:string;updated_at:string};
function CalendarView({blocks,demo}:{blocks:PlanBlock[];demo:boolean}){
  const [view,setView]=useState("日");const [events,setEvents]=useState<GoogleEvent[]>([]);const [connected,setConnected]=useState(false);const [lastSynced,setLastSynced]=useState<string|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  const load=useCallback(async()=>{if(demo)return;setLoading(true);setError("");try{const start=startOfDay(new Date());const end=addMinutes(start,24*60);const response=await fetch(`/api/calendar/events?start=${encodeURIComponent(start.toISOString())}&end=${encodeURIComponent(end.toISOString())}`);const body=await response.json() as {events?:GoogleEvent[];connected?:boolean;lastSyncedAt?:string|null;error?:string};if(!response.ok)throw new Error(body.error??"取得できませんでした");setEvents(body.events??[]);setConnected(Boolean(body.connected));setLastSynced(body.lastSyncedAt??null)}catch(value){setError(value instanceof Error?value.message:"取得できませんでした")}finally{setLoading(false)}},[demo]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  async function sync(){setLoading(true);setError("");try{const response=await fetch("/api/calendar/sync",{method:"POST"});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error??"同期できませんでした");await load()}catch(value){setError(value instanceof Error?value.message:"同期できませんでした");setLoading(false)}}
  const today=blocks.filter(block=>{const time=new Date(block.startsAt);const now=new Date();return time.toDateString()===now.toDateString()});
  return <><div className="eyebrow">Calendar</div><div className="section-title"><h1 style={{margin:0}}>カレンダー</h1><div>{["月","週","日"].map(v=><button className={`button ${view!==v?"ghost":"secondary"}`} style={{minHeight:38,padding:"0 10px"}} onClick={()=>setView(v)} key={v}>{v}</button>)}</div></div>
    <section className="card"><div className="section-title" style={{marginTop:0}}><div><h2>今日のGoogle Calendar</h2><p className="muted" style={{marginBottom:0}}>{connected?`${events.length}件 · ${lastSynced?`最終同期 ${format(new Date(lastSynced),"M/d H:mm")}`:"未同期"}`:"まだ接続されていません"}</p></div>{connected?<button className="button secondary" disabled={loading} onClick={()=>void sync()}><RefreshCw size={16}/>{loading?"同期中":"同期"}</button>:<a className="button secondary" href={demo?"#":"/api/calendar/connect"}>接続</a>}</div>{error&&<p style={{color:"var(--warn)"}}>{error}</p>}{events.length===0?<p className="muted">{loading?"予定を読み込んでいます…":"今日登録されているGoogle予定はありません。"}</p>:<div className="timeline">{events.map(event=><div className="timeline-item" key={event.id}><small>{format(new Date(event.starts_at),"H:mm")}</small><span className="timeline-line active"/><div><strong>{event.title}</strong><div className="calendar-source"><span className="pill">Google</span><span className="muted">{format(new Date(event.starts_at),"H:mm")}–{format(new Date(event.ends_at),"H:mm")}</span>{event.location&&<span className="muted">📍 {event.location}</span>}</div><small className="muted">登録先: {event.external_calendar_id}</small></div></div>)}</div>}</section>
    <section className="card" style={{marginTop:14}}><h2>ChronoPilotの今日の計画</h2><p className="muted">{view}表示 · AI提案とルールベース計画を含みます</p><div className="timeline">{today.map(b=><div className="timeline-item" key={b.id}><small>{format(new Date(b.startsAt),"H:mm")}</small><span className="timeline-line"/><div><strong>{b.title}</strong><div className="calendar-source"><span className="pill">ChronoPilot</span><span className="pill">{kindName(b.kind)}</span><span className="muted">{format(new Date(b.startsAt),"H:mm")}–{format(new Date(b.endsAt),"H:mm")}</span></div></div></div>)}</div></section></>}

function MoreView({state,setState,message,demo}:{state:LocalState;setState:React.Dispatch<React.SetStateAction<LocalState>>;message:(v:string)=>void;demo:boolean}){const [section,setSection]=useState("tasks");const sections=[['tasks','タスク',ListTodo],['projects','プロジェクト',Target],['wake','起床・外出',Sunrise],['routines','ルーティン',AlarmClock],['growth','成長',Sparkles],['balance','Life Balance',BarChart3],['review','振り返り',Moon],['settings','設定',Settings]] as const;return <><div className="eyebrow">Life OS</div><h1>その他</h1><div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:12}}>{sections.map(([id,label,Icon])=><button key={id} className={`button ${section!==id?"secondary":""}`} style={{whiteSpace:"nowrap"}} onClick={()=>setSection(id)}><Icon size={16}/>{label}</button>)}</div>{section==="tasks"&&<Tasks state={state} setState={setState}/>} {section==="projects"&&<Projects demo={demo} message={message}/>} {section==="wake"&&<Wake/>} {section==="routines"&&<Routines state={state} setState={setState} demo={demo}/>} {section==="growth"&&<Growth state={state} setState={setState}/>} {section==="balance"&&<Balance/>} {section==="review"&&<Review message={message} demo={demo}/>} {section==="settings"&&<SettingsView demo={demo} message={message}/>}</>}

function Tasks({state,setState}:{state:LocalState;setState:React.Dispatch<React.SetStateAction<LocalState>>}){return <section className="card"><div className="section-title" style={{marginTop:0}}><h2>Inbox</h2><span className="pill">{state.tasks.length}件</span></div>{state.tasks.map(t=><div className="task" key={t.id}><button aria-label="完了" className="check" onClick={()=>setState(s=>({...s,tasks:s.tasks.filter(x=>x.id!==t.id),blocks:s.blocks.map(b=>b.id===t.id?{...b,status:"done"}:b)}))}><Check size={16}/></button><div style={{flex:1}}><strong>{t.title}</strong><div className="muted" style={{fontSize:13}}>{t.estimateMinutes}分 · 優先度 {t.priority}</div></div>{t.required&&<span className="pill">必須</span>}</div>)}</section>}
function Projects({demo,message}:{demo:boolean;message:(v:string)=>void}){const [items,setItems]=useState([{id:"sample",title:"査読論文の修正",goal:"査読コメントへ回答し、品質を保って再投稿する"}]);async function add(form:FormData){const body={title:String(form.get("title")),goal:String(form.get("goal"))};if(!demo){const response=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!response.ok)return message("プロジェクトを保存できませんでした");const saved=await response.json() as {id:string;title:string;goal:string};setItems(v=>[...v,saved])}else setItems(v=>[...v,{id:crypto.randomUUID(),...body}]);message("プロジェクトを登録しました")}return <div className="grid">{items.map(item=><section className="card" key={item.id}><span className="pill">進行中</span><h2>{item.title}</h2><p className="muted">{item.goal}</p><div style={{height:8,borderRadius:8,background:"var(--panel2)"}}><div style={{width:"32%",height:"100%",borderRadius:8,background:"var(--accent)"}}/></div><p className="muted">進捗 32% · 遅延リスク：低</p></section>)}<form className="card" action={add}><h2>新しいプロジェクト</h2><div className="field"><label>名前</label><input name="title" required/></div><div className="field"><label>目標</label><textarea name="goal"/></div><button className="button">登録する</button></form></div>}
function Wake(){const first=addMinutes(startOfDay(new Date()),14*60);const plan=calculateWakePlan({firstEventAt:first,arrivalBufferMinutes:15,travelMinutes:50,departurePrepMinutes:8,morningRoutineMinutes:52,activationMinutes:10,targetSleepMinutes:420});return <div className="grid"><section className="card"><div className="eyebrow">明日の推奨</div><h2><Sunrise size={20}/> {format(plan.wakeAt,"H:mm")} 起床</h2><p>推奨就寝 {format(plan.recommendedBedtime,"H:mm")} · 出発 {format(plan.departAt,"H:mm")}</p><p className="muted">最初の予定 14:00 / 移動50分 / 到着余裕15分から逆算</p></section><section className="card"><h2><Route size={20}/> 次の外出</h2><p><strong>大学 · 田中先生との打ち合わせ</strong></p><p>出発 {format(plan.departAt,"H:mm")} → 到着 {format(addMinutes(plan.departAt,50),"H:mm")}</p><span className="pill">余裕 15分 · 遅延リスク 低</span></section></div>}
function Routines({state,setState,demo}:{state:LocalState;setState:React.Dispatch<React.SetStateAction<LocalState>>;demo:boolean}){const steps=["ベッドから出る","水を飲む","洗顔","着替え","朝食","歯磨き","荷物確認"];return <section className="card"><h2>朝ルーティン</h2>{steps.map(step=><div className="task" key={step}><button className="check" onClick={()=>{const done=!state.routineDone.includes(step);setState(s=>({...s,routineDone:done?[...s.routineDone,step]:s.routineDone.filter(x=>x!==step)}));if(done&&!demo)void sendOrQueue({url:"/api/records",method:"POST",body:{table:"routine_executions",name:step,data:{completed:true}}}).catch(()=>{})}}>{state.routineDone.includes(step)&&<Check size={16}/>}</button><span style={{textDecoration:state.routineDone.includes(step)?"line-through":"none"}}>{step}</span></div>)}</section>}
function Growth({state,setState}:{state:LocalState;setState:React.Dispatch<React.SetStateAction<LocalState>>}){return <div className="grid"><section className="card"><div className="eyebrow">長期目標</div><h2>大規模AIサービスを設計・運用できる</h2><p className="muted">3か月：分散システムの基礎を学び、本番運用する</p></section><section className="card"><h2>今日の成長タスク</h2>{state.growth.map(g=><div className="task" key={g}><button className="check" onClick={()=>setState(s=>({...s,growth:s.growth.filter(x=>x!==g)}))}><Check size={16}/></button><span>{g}</span></div>)}<div className="field"><label>成果物URL</label><input type="url" placeholder="https://github.com/..."/></div></section></div>}
function Balance(){return <section className="card"><h2>24時間の内訳</h2><div className="metric-grid"><Metric label="睡眠" value="7時間"/><Metric label="仕事・予定" value="6時間"/><Metric label="生活・移動" value="4時間"/><Metric label="可処分" value="7時間"/></div><div className="section-title"><h2>今日の自由時間</h2><span className="pill">推定</span></div><h1>3時間20分</h1><p className="muted">ゲーム 90分 · YouTube 30分 · 散歩 20分 · 完全自由 60分</p></section>}
function Review({message,demo}:{message:(v:string)=>void;demo:boolean}){const [scores,setScores]=useState<Record<string,number>>({});async function save(){if(!demo)await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({table:"daily_reflections",name:"今日の振り返り",data:scores})});message("振り返りを保存しました。データが増えるまで因果は断定しません")}return <section className="card"><h2>今日の振り返り</h2>{[["mood","気分"],["fatigue","疲労"],["focus","集中度"],["satisfaction","満足度"]].map(([key,label])=><div className="field" key={key}><label>{label}</label><div className="score-row">{[1,2,3,4,5].map(n=><button type="button" className={scores[key]===n?"selected":""} onClick={()=>setScores(s=>({...s,[key]:n}))} key={n}>{n}</button>)}</div></div>)}<div className="field"><label>できたこと</label><textarea placeholder="小さな前進も記録します"/></div><button className="button" onClick={save}>保存する</button></section>}
function vapidKey(value:string){const padding="=".repeat((4-value.length%4)%4);const raw=atob((value+padding).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)))}
function SettingsView({demo,message}:{demo:boolean;message:(v:string)=>void}){async function notifications(){if(!("Notification" in window)||!("serviceWorker" in navigator))return message("このブラウザは通知に対応していません");const permission=await Notification.requestPermission();if(permission!=="granted")return message("通知は許可されませんでした");if(demo)return message("通知を許可しました。本番接続後にPush購読を保存します");const key=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;if(!key)return message("VAPID公開鍵が設定されていません");try{const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:vapidKey(key)});const response=await fetch("/api/push/subscribe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(subscription)});message(response.ok?"通知を有効にしました":"Push購読を保存できませんでした")}catch{message("通知を有効にできませんでした。ホーム画面から再度お試しください")}}return <div className="grid"><section className="card"><h2>接続</h2><div className="task"><CalendarDays/><div style={{flex:1}}><strong>Google Calendar</strong><div className="muted">ログイン権限とは分離 · 初期値は確認して登録</div></div><a className="button secondary" href={demo?"#":"/api/calendar/connect"} onClick={e=>{if(demo){e.preventDefault();message("SupabaseとGoogle OAuth設定後に接続できます")}}}>接続</a></div><div className="task"><AlarmClock/><div style={{flex:1}}><strong>通知</strong><div className="muted">価値を確認してから許可を求めます</div></div><button className="button secondary" onClick={notifications}>設定</button></div></section><section className="card"><h2>基本設定</h2><div className="field"><label>目標睡眠</label><select defaultValue="420"><option value="420">7時間</option><option value="450">7時間30分</option><option value="480">8時間</option></select></div><div className="field"><label>平日の希望ゲーム時間</label><input type="number" defaultValue="90" min="0"/> </div><div className="field"><label>Calendar書き込み</label><select defaultValue="confirm"><option value="confirm">常に確認</option><option value="today">当日のみ自動</option><option value="all">すべて自動</option><option value="readonly">読み取り専用</option></select></div><button className="button" onClick={()=>message("設定を保存しました")}>保存</button></section></div>}
